# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/capture/capture.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==capture || ORIG_REF_NAME==capture} -quiet] -quiet

# IP: bd/capture/ip/capture_frontpanel_0_0/capture_frontpanel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==capture_frontpanel_0_0 || ORIG_REF_NAME==capture_frontpanel_0_0} -quiet] -quiet

# IP: bd/capture/ip/capture_clk_wiz_0_0/capture_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==capture_clk_wiz_0_0 || ORIG_REF_NAME==capture_clk_wiz_0_0} -quiet] -quiet

# IP: bd/capture/ip/capture_proc_sys_reset_0_1/capture_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==capture_proc_sys_reset_0_1 || ORIG_REF_NAME==capture_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/capture/ip/capture_fb_ahb_0_4/capture_fb_ahb_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==capture_fb_ahb_0_4 || ORIG_REF_NAME==capture_fb_ahb_0_4} -quiet] -quiet

# IP: bd/capture/ip/capture_axi_crossbar_0_0/capture_axi_crossbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==capture_axi_crossbar_0_0 || ORIG_REF_NAME==capture_axi_crossbar_0_0} -quiet] -quiet

# IP: bd/capture/ip/capture_axi_gpio_0_0/capture_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==capture_axi_gpio_0_0 || ORIG_REF_NAME==capture_axi_gpio_0_0} -quiet] -quiet

# IP: bd/capture/ip/capture_axi_iic_0_0/capture_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==capture_axi_iic_0_0 || ORIG_REF_NAME==capture_axi_iic_0_0} -quiet] -quiet

# IP: bd/capture/ip/capture_leds_0_0/capture_leds_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==capture_leds_0_0 || ORIG_REF_NAME==capture_leds_0_0} -quiet] -quiet

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/capture_ooc.xdc
