# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d757_phy_0_hssio_rx.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d757_phy_0_hssio_rx || ORIG_REF_NAME==bd_d757_phy_0_hssio_rx} -quiet] -quiet

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d757_phy_0_hssio_rx.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d757_phy_0_hssio_rx || ORIG_REF_NAME==bd_d757_phy_0_hssio_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d757_phy_0_hssio_rx_ooc.xdc

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d757_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d757_phy_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d757_phy_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d757_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d757_phy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d757_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d757_phy_0_hssio_rx.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d757_phy_0_hssio_rx || ORIG_REF_NAME==bd_d757_phy_0_hssio_rx} -quiet] -quiet

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d757_phy_0_hssio_rx.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d757_phy_0_hssio_rx || ORIG_REF_NAME==bd_d757_phy_0_hssio_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d757_phy_0_hssio_rx_ooc.xdc

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d757_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d757_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d757_phy_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d757_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/rob.liston/Desktop/andromeda/demo/capture/capture.gen/sources_1/bd/capture/ip/capture_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d757_phy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d757_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
